create tablespace my_tabspace  datafile 'my_tabspace.dat'  size 10M autoextend on;

create user DB_OWNER   identified by DB_OWNER   default tablespace my_tabspace;

ALTER USER DB_OWNER quota 100M on my_tabspace;


CREATE ROLE DB_OWNER_ROLE;

GRANT CREATE SESSION,ALTER SESSION,CREATE TABLE,CREATE CLUSTER,CREATE SYNONYM,CREATE VIEW,CREATE SEQUENCE,
CREATE DATABASE LINK,CREATE PROCEDURE,CREATE TRIGGER,CREATE TYPE,CREATE OPERATOR,CREATE INDEXTYPE,BACKUP ANY TABLE,
SELECT ANY TABLE,CREATE ANY TABLE,CREATE ANY INDEX,ALTER ANY INDEX,ALTER ANY INDEXTYPE,DROP ANY INDEX,DROP ANY INDEXTYPE to DB_OWNER_ROLE;

GRANT DB_OWNER_ROLE to DB_OWNER;




